.TH DICL 1 2021-07-29
.SH NAME
dicl \- command-line interface for selected online dictionaries
.
.SH SYNOPSIS
.SY dicl
.IR TERM...
.YS
.
.SH DESCRIPTION
Look up the definition of \fTERM\fR in supported online dictionaries
and display the results in terminal.
.
.SH OPTIONS
.TP 4
.B \-\-version
Print version and exit.
.TP
.B \-v, \-\-verbose
Increase verbosity.
